From ubuntu:14.04.2

copy . /tmp

env testuniqseparat true
env testuniq=true

env test=true key=value 

env test2 this is the string of the test2 env value

env usage="test string for export"
# comment
toto

titi

